### ISSUE TITLE
entity-security.rst

### ISSUE THREAD

**Issue by roukmoute** [knpuniversity/symfony2-ep2#6]
On your document entity-security.rst, your link for DependencyInjectionContainerAwareInterface` is not correct.
It's a redirection on this : http://api.symfony.com/2.3/Symfony/Component/DependencyInjectionContainerAwareInterface%60.html

Correct (and new) URL is : http://api.symfony.com/2.4/Symfony/Component/DependencyInjection/ContainerAwareInterface.html

**Comment by weaverryan** [comment]
Thanks Mathias! I fixed the syntax error with the link and bumped our Symfony API version: http://knpuniversity.com/screencast/symfony2-ep2/entity-security#creating-and-saving-users

Thanks for the report!
